# Datenbank-Typ: "yaml" oder "mysql"
storage-type: yaml

# Aliasse für den Multiowner-Command
command-aliases:
  - Coowner

mysql:
  host: localhost
  port: 3306
  database: minecraft
  user: root
  password: password


